# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Report1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import UniversalVar
from PyQt5 import QtCore, QtWidgets

class PandasModel(QtCore.QAbstractTableModel):
    """
    Class to populate a table view with a pandas dataframe
    """
    def __init__(self, data, parent=None):
        QtCore.QAbstractTableModel.__init__(self, parent)
        self._data = data

    def rowCount(self, parent=None):
        return self._data.shape[0]

    def columnCount(self, parent=None):
        return self._data.shape[1]

    def data(self, index, role=QtCore.Qt.DisplayRole):
        if index.isValid():
            if role == QtCore.Qt.DisplayRole:
                return str(self._data.iloc[index.row(), index.column()])
        return None

    def headerData(self, col, orientation, role):
        if orientation == QtCore.Qt.Horizontal and role == QtCore.Qt.DisplayRole:
            return self._data.columns[col]
        return None


class Ui_MainWindow_3(object):
    def setupUi(self, MainWindow_3, resultdf):
        MainWindow_3.setObjectName("MainWindow_3")
        MainWindow_3.resize(679, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow_3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(562, 357, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(633, 355, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 390, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(339, 407, 251, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(9, 358, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 393, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(151, 359, 121, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(103, 360, 41, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(269, 359, 31, 17))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(599, 408, 67, 17))
        self.label_11.setObjectName("label_11")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(5, 1, 671, 351))
        self.tableView.setObjectName("tableView")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(5, 1, 671, 351))
        self.tableView.setObjectName("tableView")
        self.model = PandasModel(resultdf)
        self.tableView.setModel(self.model)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(9, 411, 141, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 411, 67, 17))
        self.label_13.setObjectName("label_13")
        MainWindow_3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        MainWindow_3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_3)
        self.statusbar.setObjectName("statusbar")
        MainWindow_3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_3)

    def retranslateUi(self, MainWindow_3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_3.setWindowTitle(_translate("MainWindow_3", "Report"))
        self.label.setText(_translate("MainWindow_3", "Win Rate :"))
        self.label_2.setText(_translate("MainWindow_3", str("{:.2f}".format((UniversalVar.totalwin / UniversalVar.tradecount) * 100))))
        self.label_3.setText(_translate("MainWindow_3", "Losing Trades (no.) :"))
        self.label_4.setText(_translate("MainWindow_3", "Points for contanst Position Sizing  :"))
        self.label_5.setText(_translate("MainWindow_3", "Total Trades :"))
        self.label_6.setText(_translate("MainWindow_3", str(UniversalVar.totallose)))
        self.label_7.setText(_translate("MainWindow_3", "Stocks Scanned :"))
        self.label_8.setText(_translate("MainWindow_3", str(UniversalVar.tradecount)))
        self.label_9.setText(_translate("MainWindow_3", str(UniversalVar.stockcount)))
        self.label_11.setText(_translate("MainWindow_3", str("{:.2f}".format(UniversalVar.points))))
        self.label_12.setText(_translate("MainWindow_3", "Winning Trades (no.) :"))
        self.label_13.setText(_translate("MainWindow_3", str(UniversalVar.totalwin)))
