# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserGuideWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_4(object):
    def setupUi(self, MainWindow_4):
        MainWindow_4.setObjectName("MainWindow_4")
        MainWindow_4.resize(559, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow_4)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(11, 50, 541, 31))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 551, 41))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 541, 51))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 216, 531, 61))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 276, 521, 31))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 531, 31))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 511, 41))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 311, 451, 17))
        self.label_8.setObjectName("label_8")
        MainWindow_4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 22))
        self.menubar.setObjectName("menubar")
        MainWindow_4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_4)
        self.statusbar.setObjectName("statusbar")
        MainWindow_4.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_4)

    def retranslateUi(self, MainWindow_4):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_4.setWindowTitle(_translate("MainWindow_4", "User Guide"))
        self.label_7.setText(_translate("MainWindow_4", "- Target price & Stop Loss is a value, which is x% away from Entry Price"))
        self.label_10.setText(_translate("MainWindow_4", "- Days : Gives \'x\' (no. of) Days High or Low Dependeding on Candlestick Pattern Selected"))
        self.label_2.setText(_translate("MainWindow_4", "- Pinbar/HangingMan/BearEngulf/BullEngulf are candlestick Pattern which comes under Technical Analysis of Intraday trading"))
        self.label_3.setText(_translate("MainWindow_4", "Example : if we select Pinbar, choose to sell and Enter 10 Days, it will detect Pinbar shaped candle which is higher than 10 previous candles within 2 years of data inside stocks folder for every stock"))
        self.label_4.setText(_translate("MainWindow_4", "- Next Open/ Close : Desired point to enter trade"))
        self.label_5.setText(_translate("MainWindow_4", "- For Pinbar/BearEngulf it detects Highs and for HangingMan/BullEngulf it detects lows"))
        self.label_6.setText(_translate("MainWindow_4", "\"If below Information is not informative enough then use dafault values, Browse to \'stocks\' folder, choose Buy/Sell and Hit Get Report\""))
        self.label_8.setText(_translate("MainWindow_4", "- Lower Limit and Upper Limit: range within which we wish to trade"))
